version: "2"
services:
    aptly:
        container_name: aptly
        image: byted/aptly:latest
        restart: always
        ports:
            - 80:80
        volumes:
            - /opt/aptly_files:/opt/aptly
            - ./assets/scripts:/opt/scripts
        environment:
            - HOSTNAME=apt.byted.org
            - FULL_NAME="byted.org"
            - EMAIL_ADDRESS="admin@byed.org"
            - GPG_PASSWORD="PickAPassword"
